name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd terraform/environments/dev
          terraform init

      - name: Clean Up Resources
        run: |
          cd terraform/environments/dev
          
          # Empty S3 bucket first
          aws s3 rm s3://recipe-storage-dev --recursive || true
          
          # Disable all CloudFront distributions
          for DIST_ID in E1R89VII6SDI4C E7B71H3JZDHLH; do
            CONFIG=$(aws cloudfront get-distribution --id $DIST_ID --query 'Distribution.DistributionConfig')
            ETAG=$(aws cloudfront get-distribution --id $DIST_ID --query 'Distribution.ETag' --output text)
            echo "$CONFIG" | sed 's/"Enabled": true/"Enabled": false/' > tmp_config.json
            aws cloudfront update-distribution --id $DIST_ID --distribution-config file://tmp_config.json --if-match "$ETAG" || true
          done
          
          # Delete CloudFront Origin Access Identities
          for OAI in E3J41MD19IG6S; do
            aws cloudfront delete-cloud-front-origin-access-identity --id $OAI --if-match $(aws cloudfront get-cloud-front-origin-access-identity --id $OAI --query 'ETag' --output text) || true
          done
          
          # Clean up config files
          rm -f config.json new_config.json tmp_config.json || true
          
          # Import resources
          terraform import module.storage.aws_s3_bucket.recipe_storage recipe-storage-dev || true
          terraform import module.processing.aws_lambda_function.recipe_processor recipe_processor_dev || true
          terraform import module.distribution.aws_cloudfront_distribution.recipe_distribution E1R89VII6SDI4C || true
          terraform import module.distribution.aws_cloudfront_distribution.recipe_distribution E7B71H3JZDHLH || true

      - name: Terraform Destroy
        run: |
          cd terraform/environments/dev
          terraform destroy -auto-approve \
            -var="environment=dev" \
            -var="project=CIRCU-LI-ION" \
            -var="customer_ip=35.164.185.122"

      - name: Final Cleanup
        run: |
          # Delete any remaining CloudFront distributions
          for DIST_ID in $(aws cloudfront list-distributions --query 'DistributionList.Items[*].Id' --output text); do
            aws cloudfront delete-distribution --id $DIST_ID --if-match $(aws cloudfront get-distribution --id $DIST_ID --query 'Distribution.ETag' --output text) || true
          done
          
          # Delete any remaining S3 buckets
          aws s3 rb s3://recipe-storage-dev --force || true
          
          # Delete any remaining Lambda functions
          aws lambda delete-function --function-name recipe_processor_dev || true