name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Find Resources
        run: |
          echo "Finding Lambda functions..."
          LAMBDA_FUNCTIONS=$(aws lambda list-functions --query 'Functions[?starts_with(FunctionName, `recipe_processor_`)].FunctionName' --output text)
          for FUNC in $LAMBDA_FUNCTIONS; do
            echo "Found Lambda function: $FUNC"
          done
          
          echo "Checking S3 buckets..."
          BUCKETS=$(aws s3api list-buckets --query 'Buckets[?starts_with(Name, `recipe-storage-`)].Name' --output text)
          for BUCKET in $BUCKETS; do
            echo "Found S3 bucket: $BUCKET"
            aws s3api get-bucket-location --bucket $BUCKET
          done

      - name: Terraform Init and Destroy
        run: |
          cd terraform/environments/dev
          terraform init
          terraform destroy -auto-approve