name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd terraform/environments/dev
          terraform init

      - name: Import and Destroy Resources
        run: |
          cd terraform/environments/dev
          
          # Import existing resources
          terraform import module.storage.aws_s3_bucket.recipe_storage recipe-storage-dev
          terraform import module.processing.aws_lambda_function.recipe_processor recipe_processor_dev
          terraform import module.distribution.aws_cloudfront_distribution.recipe_distribution E2U3P18FNGKJHS
          
          # Destroy everything
          terraform destroy -auto-approve \
            -var="environment=dev" \
            -var="project=CIRCU-LI-ION" \
            -var="customer_ip=35.164.185.122"