name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd terraform/environments/dev
          terraform init

      - name: Empty S3 Bucket
        run: |
          aws s3 rm s3://circu-li-ion-recipe-storage-dev --recursive || true

      - name: Disable CloudFront Distribution
        run: |
          DIST_ID=$(aws cloudfront list-distributions --query 'DistributionList.Items[?Comment!=`null`].Id' --output text)
          if [ ! -z "$DIST_ID" ]; then
            CONFIG=$(aws cloudfront get-distribution --id $DIST_ID --query 'Distribution.DistributionConfig' | sed 's/"Enabled": true/"Enabled": false/')
            ETAG=$(aws cloudfront get-distribution --id $DIST_ID --query 'Distribution.ETag' --output text)
            echo "$CONFIG" > config.json
            aws cloudfront update-distribution --id $DIST_ID --distribution-config file://config.json --if-match "$ETAG"
          fi

      - name: Terraform Destroy
        run: |
          cd terraform/environments/dev
          terraform destroy -auto-approve \
            -var="environment=dev" \
            -var="project=CIRCU-LI-ION" \
            -var="customer_ip=35.164.185.122"