name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (dev/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      confirmation:
        description: 'Type "DESTROY" to confirm deletion of all resources'
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirmation == 'DESTROY'
    environment: ${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        working-directory: recipe-automation/terraform/environments/${{ github.event.inputs.environment }}
        run: |
          cat > backend.tf << EOF
          terraform {
            backend "s3" {
              bucket         = "${{ secrets.TERRAFORM_STATE_BUCKET }}"
              key            = "recipe-automation/${{ github.event.inputs.environment }}/terraform.tfstate"
              region         = "us-west-2"
              dynamodb_table = "${{ secrets.TERRAFORM_LOCK_TABLE }}"
              encrypt        = true
            }
          }
          EOF
          terraform init

      - name: Force Empty S3 Buckets
        working-directory: recipe-automation/terraform/environments/${{ github.event.inputs.environment }}
        run: |
          # Get all bucket names from terraform state
          BUCKETS=$(terraform show -json | jq -r '.values.root_module.child_modules[].resources[] | select(.type == "aws_s3_bucket") | .values.id')
          
          for bucket in $BUCKETS; do
            echo "Forcefully emptying bucket: $bucket"
            
            # Remove bucket versioning first
            aws s3api put-bucket-versioning --bucket "$bucket" --versioning-configuration Status=Suspended

            # Delete all objects including versions and delete markers
            aws s3api list-object-versions --bucket "$bucket" --output json 2>/dev/null | \
            jq -r '.Versions?[]? | "\(.Key) \(.VersionId)" | select(. != null)' | \
            while read -r key version; do
              echo "Deleting object: $key version: $version"
              aws s3api delete-object --bucket "$bucket" --key "$key" --version-id "$version" --bypass-governance-retention
            done

            # Delete delete markers
            aws s3api list-object-versions --bucket "$bucket" --output json 2>/dev/null | \
            jq -r '.DeleteMarkers?[]? | "\(.Key) \(.VersionId)" | select(. != null)' | \
            while read -r key version; do
              echo "Deleting delete marker: $key version: $version"
              aws s3api delete-object --bucket "$bucket" --key "$key" --version-id "$version" --bypass-governance-retention
            done

            # Delete any remaining objects (non-versioned)
            echo "Removing any remaining objects..."
            aws s3 rm s3://"$bucket" --recursive --force

            echo "Bucket $bucket emptied"
          done

      - name: Destroy Infrastructure
        working-directory: recipe-automation/terraform/environments/${{ github.event.inputs.environment }}
        env:
          TF_VAR_project_name: recipe-automation
          TF_VAR_environment: ${{ github.event.inputs.environment }}
        run: terraform destroy -auto-approve

      - name: Clean up Terraform state
        if: success()
        run: |
          aws s3 rm s3://${{ secrets.TERRAFORM_STATE_BUCKET }}/recipe-automation/${{ github.event.inputs.environment }}/terraform.tfstate --force
          aws dynamodb delete-item \
            --table-name ${{ secrets.TERRAFORM_LOCK_TABLE }} \
            --key '{"LockID": {"S": "recipe-automation/${{ github.event.inputs.environment }}/terraform.tfstate-md5"}}'
