name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd terraform/environments/dev
          terraform init

      - name: Clean Up CloudFront
        run: |
          # Function to disable distribution
          disable_distribution() {
            local DIST_ID=$1
            
            # Get current config
            local CONFIG=$(aws cloudfront get-distribution-config --id $DIST_ID)
            local ETAG=$(echo "$CONFIG" | jq -r '.ETag')
            local DIST_CONFIG=$(echo "$CONFIG" | jq -r '.DistributionConfig')
            
            # Create new config with Enabled=false
            echo "$DIST_CONFIG" | jq '.Enabled = false' > config.json
            
            # Update distribution
            aws cloudfront update-distribution \
              --id $DIST_ID \
              --if-match "$ETAG" \
              --distribution-config file://config.json
          }
          
          # Disable each distribution
          for DIST_ID in E7B71H3JZDHLH E1R89VII6SDI4C; do
            echo "Disabling distribution $DIST_ID..."
            disable_distribution $DIST_ID || true
            sleep 30
          done

      - name: Clean Up IAM
        run: |
          # Delete IAM user policies
          aws iam list-user-policies --user-name recipe-customer-dev | jq -r '.PolicyNames[]' | while read policy; do
            aws iam delete-user-policy --user-name recipe-customer-dev --policy-name "$policy"
          done
          
          # Delete IAM user
          aws iam delete-user --user-name recipe-customer-dev || true

      - name: Clean Up CloudWatch
        run: |
          # Delete CloudWatch Log Groups
          aws logs delete-log-group --log-group-name /aws/lambda/recipe_processor_dev || true
          
          # Delete CloudWatch Alarms
          aws cloudwatch delete-alarms --alarm-names CIRCU-LI-ION-lambda-errors || true

      - name: Clean Up SNS
        run: |
          # Delete SNS topics
          TOPIC_ARN=$(aws sns list-topics --query 'Topics[?contains(TopicArn,`lambda-alerts-dev`)].[TopicArn]' --output text)
          if [ ! -z "$TOPIC_ARN" ]; then
            aws sns delete-topic --topic-arn "$TOPIC_ARN"
          fi

      - name: Wait for CloudFront
        run: |
          echo "Waiting for CloudFront distributions to be disabled..."
          sleep 300  # Wait 5 minutes

      - name: Delete CloudFront
        run: |
          # Function to delete distribution
          delete_distribution() {
            local DIST_ID=$1
            local ETAG=$(aws cloudfront get-distribution --id $DIST_ID --query 'Distribution.ETag' --output text 2>/dev/null)
            
            if [ ! -z "$ETAG" ]; then
              aws cloudfront delete-distribution --id $DIST_ID --if-match "$ETAG"
            fi
          }
          
          # Delete each distribution
          for DIST_ID in E7B71H3JZDHLH E1R89VII6SDI4C; do
            echo "Deleting distribution $DIST_ID..."
            delete_distribution $DIST_ID || true
          done

      - name: Final Resource Cleanup
        run: |
          # Delete Lambda functions
          aws lambda delete-function --function-name recipe_processor_dev || true
          
          # Delete S3 buckets
          aws s3 rb s3://recipe-storage-dev --force || true
          
          # Delete CloudFront Origin Access Identities
          for OAI in E3J41MD19IG6S E3JVHJN7DHO9I2; do
            ETAG=$(aws cloudfront get-cloud-front-origin-access-identity --id $OAI --query 'ETag' --output text 2>/dev/null)
            if [ ! -z "$ETAG" ]; then
              aws cloudfront delete-cloud-front-origin-access-identity --id $OAI --if-match "$ETAG" || true
            fi
          done