name: Terraform Deployment

on:
  push:
    branches:
      - main  # Run this workflow on push to main branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Update to match your Terraform version

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environments/dev

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: terraform/environments/dev

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform/environments/dev

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: terraform/environments/dev

