name: Terraform Deployment

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Prepare Lambda Function
        run: |
          echo "Creating Lambda function package..."
          cd terraform/src/lambda_function
          
          # Install dependencies
          npm install
          
          # Create zip file
          zip -r lambda_function.zip .
          
          # Move zip to correct location
          mv lambda_function.zip ..
          
          # Verify zip exists
          ls -la ../lambda_function.zip
        working-directory: ${{ github.workspace }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environments/dev

      - name: Terraform Refresh
        run: terraform refresh -var="environment=dev" -var="project=CIRCU-LI-ION" -var="customer_ip=35.164.185.122"
        working-directory: terraform/environments/dev

      - name: Import Existing AWS Resources (if needed)
        run: |
          terraform import module.processing.aws_iam_role.lambda_role recipe_processor_role_dev || true
          terraform import module.processing.aws_cloudwatch_log_group.lambda_logs /aws/lambda/CIRCU-LI-ION-recipe-processor || true
          terraform import module.storage.aws_s3_bucket.recipe_storage recipe-storage-dev || true
          terraform import module.storage.aws_iam_user.customer recipe-customer-dev || true
          terraform import module.processing.aws_lambda_function.recipe_processor recipe_processor_dev || true
        working-directory: terraform/environments/dev

      - name: Check and Import Lambda Resources
        run: |
          # Check if Lambda exists
          if aws lambda get-function --function-name recipe_processor_dev &>/dev/null; then
            echo "Lambda exists, importing resources..."
            
            # Import Lambda function
            terraform import module.processing.aws_lambda_function.recipe_processor recipe_processor_dev || true
            
            # Import Lambda permissions
            terraform import "module.processing.aws_lambda_permission.allow_s3" "recipe_processor_dev/AllowExecutionFromS3Bucket-dev" || true
            terraform import "module.processing.aws_lambda_permission.allow_bucket" "recipe_processor_dev/AllowS3Invoke-dev" || true
            
            # List existing permissions for verification
            aws lambda get-policy --function-name recipe_processor_dev || true
          else
            echo "Lambda doesn't exist, will be created by Terraform"
          fi
        working-directory: terraform/environments/dev

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var="environment=dev" -var="project=CIRCU-LI-ION" -var="customer_ip=35.164.185.122"
        working-directory: terraform/environments/dev

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/environments/dev

