name: 'Test Infrastructure'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    outputs:
      test_status: ${{ job.status }}  # Output test status for deploy workflow

    env:
      OUTPUT_BUCKET: 'test-bucket'
      ENVIRONMENT: 'test'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd src/processor
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Python tests
      run: |
        cd src/processor
        python -m pytest tests/ -v

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.0.0'

    - name: Terraform Format
      run: |
        cd terraform
        terraform fmt -check

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate 